---@diagnostic disable: exp-in-action, unknown-symbol
---@description Prompt Studio Dynamic IPLs Presets [https://store.prompt-mods.com/]

['sandy_motel'] = {
    coords = vec3(1609.9529, 3773.4612, 37.50),
    size = vec3(35.0, 90.0, 7.0),
    rotation = 127.5,
    debug = false,
    ipl = {
        'prompt_sandy_motel_room_1',
        'prompt_sandy_motel_room_2',
        'prompt_sandy_motel_room_3',
        'prompt_sandy_motel_room_4',
        'prompt_sandy_motel_room_5',
        'prompt_sandy_motel_room_6',
        'prompt_sandy_motel_room_7',
        'prompt_sandy_motel_room_8',
        'prompt_sandy_motel_room_9',
        'prompt_sandy_motel_room_10',
        'prompt_sandy_motel_room_11',
        'prompt_sandy_motel_room_12',
        'prompt_sandy_motel_room_13',
        'prompt_sandy_motel_room_14',
        'prompt_sandy_motel_room_15',
        'prompt_sandy_motel_room_16',
        'prompt_sandy_motel_room_17',
        'prompt_sandy_motel_room_18',
        'prompt_sandy_motel_room_19',
        'prompt_sandy_motel_room_20',
        'prompt_sandy_motel_room_21',
        'prompt_sandy_motel_room_22',
        'prompt_sandy_motel_room_23',
        'prompt_sandy_motel_room_24',
        'prompt_sandy_motel_room_25',
        'prompt_sandy_motel_room_26',
        'prompt_sandy_motel_room_27',
        'prompt_sandy_motel_room_28',
        'prompt_sandy_motel_room_29',
        'prompt_sandy_motel_room_30',
        'prompt_sandy_motel_room_31',
        'prompt_sandy_motel_room_32',
    },
},