---@diagnostic disable: exp-in-action, unknown-symbol
---@description TStudio IPLs Presets [https://shop.tstudio3d.com/]

---@description Static IPLs
['legion_square'] = {
    ['default'] = { ipl = 'tstudio_legionsquare_ext_amphi_default', default = true },
    ['band'] = { ipl = 'tstudio_legionsquare_ext_amphi_band', default = true },
    ['dj'] = { ipl = 'tstudio_legionsquare_ext_amphi_dj', default = true },
    ['speaker'] = { ipl = 'tstudio_legionsquare_ext_amphi_speaker', default = true },
},

---@description Dynamic IPLs
['opium_nights_hotel_1'] = {
    coords = vec3(-720.0649, -2263.3970, 31.20),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e01_milo_',
        'johanni_opium_hallway_e01_milo_',
        'johanni_opium_hotel_e01_r01_milo_',
        'johanni_opium_hotel_e01_r02_milo_',
        'johanni_opium_hotel_e01_r03_milo_',
        'johanni_opium_hotel_e01_r04_milo_',
        'johanni_opium_hotel_e01_r05_milo_',
        'johanni_opium_hotel_e01_r06_milo_',
        'johanni_opium_hotel_e01_r07_milo_',
        'johanni_opium_hotel_e01_r08_milo_',
        'johanni_opium_hotel_e01_r09_milo_',
        'johanni_opium_hotel_e01_r10_milo_',
        'johanni_opium_hotel_e01_r11_milo_',
        'johanni_opium_hotel_e01_r12_milo_',
    },
},

['opium_nights_hotel_2'] = {
    coords = vec3(-720.0649, -2263.3970, 40.20),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e02_milo_',
        'johanni_opium_hallway_e02_milo_',
        'johanni_opium_hotel_e02_r01_milo_',
        'johanni_opium_hotel_e02_r02_milo_',
        'johanni_opium_hotel_e02_r03_milo_',
        'johanni_opium_hotel_e02_r04_milo_',
        'johanni_opium_hotel_e02_r05_milo_',
        'johanni_opium_hotel_e02_r06_milo_',
        'johanni_opium_hotel_e02_r07_milo_',
        'johanni_opium_hotel_e02_r08_milo_',
        'johanni_opium_hotel_e02_r09_milo_',
        'johanni_opium_hotel_e02_r10_milo_',
        'johanni_opium_hotel_e02_r11_milo_',
        'johanni_opium_hotel_e02_r12_milo_',
    },
},

['opium_nights_hotel_3'] = {
    coords = vec3(-720.0649, -2263.3970, 49.00),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e03_milo_',
        'johanni_opium_hallway_e03_milo_',
        'johanni_opium_hotel_e03_r01_milo_',
        'johanni_opium_hotel_e03_r02_milo_',
        'johanni_opium_hotel_e03_r03_milo_',
        'johanni_opium_hotel_e03_r04_milo_',
        'johanni_opium_hotel_e03_r05_milo_',
        'johanni_opium_hotel_e03_r06_milo_',
        'johanni_opium_hotel_e03_r07_milo_',
        'johanni_opium_hotel_e03_r08_milo_',
        'johanni_opium_hotel_e03_r09_milo_',
        'johanni_opium_hotel_e03_r10_milo_',
        'johanni_opium_hotel_e03_r11_milo_',
        'johanni_opium_hotel_e03_r12_milo_',
    },
},

['opium_nights_hotel_4'] = {
    coords = vec3(-720.0649, -2263.3970, 58.00),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e04_milo_',
        'johanni_opium_hallway_e04_milo_',
        'johanni_opium_hotel_e04_r01_milo_',
        'johanni_opium_hotel_e04_r02_milo_',
        'johanni_opium_hotel_e04_r03_milo_',
        'johanni_opium_hotel_e04_r04_milo_',
        'johanni_opium_hotel_e04_r05_milo_',
        'johanni_opium_hotel_e04_r06_milo_',
        'johanni_opium_hotel_e04_r07_milo_',
        'johanni_opium_hotel_e04_r08_milo_',
        'johanni_opium_hotel_e04_r09_milo_',
        'johanni_opium_hotel_e04_r10_milo_',
        'johanni_opium_hotel_e04_r11_milo_',
        'johanni_opium_hotel_e04_r12_milo_',
    },
},

['opium_nights_hotel_5'] = {
    coords = vec3(-720.0649, -2263.3970, 66.70),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e05_milo_',
        'johanni_opium_hallway_e05_milo_',
        'johanni_opium_hotel_e05_r01_milo_',
        'johanni_opium_hotel_e05_r02_milo_',
        'johanni_opium_hotel_e05_r03_milo_',
        'johanni_opium_hotel_e05_r04_milo_',
        'johanni_opium_hotel_e05_r05_milo_',
        'johanni_opium_hotel_e05_r06_milo_',
        'johanni_opium_hotel_e05_r07_milo_',
        'johanni_opium_hotel_e05_r08_milo_',
        'johanni_opium_hotel_e05_r09_milo_',
        'johanni_opium_hotel_e05_r10_milo_',
        'johanni_opium_hotel_e05_r11_milo_',
        'johanni_opium_hotel_e05_r12_milo_',
    },
},

['opium_nights_hotel_6'] = {
    coords = vec3(-720.0649, -2263.3970, 75.60),
    size = vec3(110.0, 130.0, 4.0),
    rotation = 180.0,
    debug = false,
    ipl = {
        'johanni_opium_penthouse_e06_milo_',
        'johanni_opium_hallway_e06_milo_',
        'johanni_opium_hotel_e06_r01_milo_',
        'johanni_opium_hotel_e06_r02_milo_',
        'johanni_opium_hotel_e06_r03_milo_',
        'johanni_opium_hotel_e06_r04_milo_',
        'johanni_opium_hotel_e06_r05_milo_',
        'johanni_opium_hotel_e06_r06_milo_',
        'johanni_opium_hotel_e06_r07_milo_',
        'johanni_opium_hotel_e06_r08_milo_',
        'johanni_opium_hotel_e06_r09_milo_',
        'johanni_opium_hotel_e06_r10_milo_',
        'johanni_opium_hotel_e06_r11_milo_',
        'johanni_opium_hotel_e06_r12_milo_',
    },
},